/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/entities/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Entities Endpoint */
        get: operations["get_entities_endpoint_entities__get"];
        put?: never;
        /** Create Entity Endpoint */
        post: operations["create_entity_endpoint_entities__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entities/{entity_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Entity Endpoint */
        get: operations["get_entity_endpoint_entities__entity_id__get"];
        /** Update Entity Endpoint */
        put: operations["update_entity_endpoint_entities__entity_id__put"];
        post?: never;
        /** Delete Entity Endpoint */
        delete: operations["delete_entity_endpoint_entities__entity_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stances/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Stances Endpoint */
        get: operations["get_stances_endpoint_stances__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stances/feed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Get Stance Feed Endpoint */
        post: operations["get_stance_feed_endpoint_stances_feed_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stances/following-feed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Stance Feed Endpoint */
        get: operations["get_stance_feed_endpoint_stances_following_feed_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{user_id}/stances/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get User Stances Endpoint */
        get: operations["get_user_stances_endpoint_users__user_id__stances__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entities/{entity_id}/stances/{stance_id}/my-rating": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get My Stance Rating Endpoint */
        get: operations["get_my_stance_rating_endpoint_entities__entity_id__stances__stance_id__my_rating_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entities/{entity_id}/stances/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Entity Stances Endpoint */
        get: operations["get_entity_stances_endpoint_entities__entity_id__stances__get"];
        put?: never;
        /** Create Stance Endpoint */
        post: operations["create_stance_endpoint_entities__entity_id__stances__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entities/{entity_id}/stances/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get My Stance For Entity */
        get: operations["get_my_stance_for_entity_entities__entity_id__stances_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entities/{entity_id}/stances/{stance_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Stance Basic Endpoint */
        get: operations["get_stance_basic_endpoint_entities__entity_id__stances__stance_id__get"];
        /** Update Stance Endpoint */
        put: operations["update_stance_endpoint_entities__entity_id__stances__stance_id__put"];
        post?: never;
        /** Delete Stance Endpoint */
        delete: operations["delete_stance_endpoint_entities__entity_id__stances__stance_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entities/{entity_id}/stances/{stance_id}/page": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Stance Endpoint */
        get: operations["get_stance_endpoint_entities__entity_id__stances__stance_id__page_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entities/{entity_id}/stances/{stance_id}/rate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rate Stance Endpoint */
        post: operations["rate_stance_endpoint_entities__entity_id__stances__stance_id__rate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entities/{entity_id}/stances/{stance_id}/num-ratings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Num Ratings Endpoint */
        get: operations["get_num_ratings_endpoint_entities__entity_id__stances__stance_id__num_ratings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Current User Endpoint */
        get: operations["get_current_user_endpoint_users_me_get"];
        /** Update Current User Endpoint */
        put: operations["update_current_user_endpoint_users_me_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/username_taken": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Check Username Endpoint */
        get: operations["check_username_endpoint_users_username_taken_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get User Endpoint */
        get: operations["get_user_endpoint_users__user_id__get"];
        put?: never;
        post?: never;
        /** Delete User Endpoint */
        delete: operations["delete_user_endpoint_users__user_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{user_id}/demographics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Demographic Endpoint */
        get: operations["get_demographic_endpoint_users__user_id__demographics_get"];
        /** Update Demographic Endpoint */
        put: operations["update_demographic_endpoint_users__user_id__demographics_put"];
        /** Create Demographic Endpoint */
        post: operations["create_demographic_endpoint_users__user_id__demographics_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{user_id}/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Profile Endpoint */
        get: operations["get_profile_endpoint_users__user_id__profile_get"];
        /** Update Profile Endpoint */
        put: operations["update_profile_endpoint_users__user_id__profile_put"];
        /** Create Profile Endpoint */
        post: operations["create_profile_endpoint_users__user_id__profile_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{user_id}/profile_page": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Profile Page Endpoint */
        get: operations["get_profile_page_endpoint_users__user_id__profile_page_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{user_id}/follow": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Follow User Endpoint */
        post: operations["follow_user_endpoint_users__user_id__follow_post"];
        /** Unfollow User Endpoint */
        delete: operations["unfollow_user_endpoint_users__user_id__follow_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{user_id}/followers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Followers Endpoint */
        get: operations["get_followers_endpoint_users__user_id__followers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{user_id}/following": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Following Endpoint */
        get: operations["get_following_endpoint_users__user_id__following_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{user_id}/following/{followed_user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Is Following Endpoint */
        get: operations["is_following_endpoint_users__user_id__following__followed_user_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Signup */
        post: operations["signup_auth_signup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Token */
        post: operations["token_auth_token_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh Token */
        post: operations["refresh_token_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset Password */
        post: operations["reset_password_auth_change_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entities/{entity_id}/stances/{stance_id}/comments/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Comments Endpoint */
        get: operations["get_comments_endpoint_entities__entity_id__stances__stance_id__comments__get"];
        put?: never;
        /** Create Comment Endpoint */
        post: operations["create_comment_endpoint_entities__entity_id__stances__stance_id__comments__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entities/{entity_id}/stances/{stance_id}/comments/{comment_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Comment Endpoint */
        get: operations["get_comment_endpoint_entities__entity_id__stances__stance_id__comments__comment_id__get"];
        /** Update Comment Endpoint */
        put: operations["update_comment_endpoint_entities__entity_id__stances__stance_id__comments__comment_id__put"];
        post?: never;
        /** Delete Comment Endpoint */
        delete: operations["delete_comment_endpoint_entities__entity_id__stances__stance_id__comments__comment_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entities/{entity_id}/stances/{stance_id}/comments/{comment_id}/replies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Comment Replies Endpoint */
        get: operations["get_comment_replies_endpoint_entities__entity_id__stances__stance_id__comments__comment_id__replies_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entities/{entity_id}/stances/{stance_id}/comments/{comment_id}/reaction": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** React To Comment */
        post: operations["react_to_comment_entities__entity_id__stances__stance_id__comments__comment_id__reaction_post"];
        /** Remove Comment Reaction */
        delete: operations["remove_comment_reaction_entities__entity_id__stances__stance_id__comments__comment_id__reaction_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/images": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Image Endpoint */
        post: operations["create_image_endpoint_images_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_token_auth_token_post */
        Body_token_auth_token_post: {
            /** Grant Type */
            grant_type?: string | null;
            /** Username */
            username: string;
            /**
             * Password
             * Format: password
             */
            password: string;
            /**
             * Scope
             * @default
             */
            scope: string;
            /** Client Id */
            client_id?: string | null;
            /**
             * Client Secret
             * Format: password
             */
            client_secret?: string | null;
        };
        /** ChangePasswordRequest */
        ChangePasswordRequest: {
            /** Current Password */
            current_password: string;
            /** New Password */
            new_password: string;
        };
        /** CommentCreateRequest */
        CommentCreateRequest: {
            /** Content */
            content: string;
            /** Parent Id */
            parent_id?: number | null;
        };
        /** CommentListResponse */
        CommentListResponse: {
            /** Comments */
            comments: components["schemas"]["CommentReadResponse"][];
        };
        /** CommentReactionCreateRequest */
        CommentReactionCreateRequest: {
            /** Is Like */
            is_like: boolean;
        };
        /** CommentReadResponse */
        CommentReadResponse: {
            /** Id */
            id: number;
            /** User Id */
            user_id: number;
            /** Stance Id */
            stance_id: number;
            /** Content */
            content: string;
            /** Parent Id */
            parent_id?: number | null;
            /** Is Active */
            is_active: boolean;
            /** Likes */
            likes: number;
            /** Dislikes */
            dislikes: number;
            /** User Reaction */
            user_reaction: string | null;
            /** Count Nested */
            count_nested: number;
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at: string | null;
        };
        /** CommentUpdateRequest */
        CommentUpdateRequest: {
            /** Content */
            content?: string | null;
            /** Is Active */
            is_active?: boolean | null;
        };
        /** CommentUpdateResponse */
        CommentUpdateResponse: {
            /** Id */
            id: number;
            /** User Id */
            user_id: number;
            /** Stance Id */
            stance_id: number;
            /** Content */
            content: string;
            /** Parent Id */
            parent_id?: number | null;
            /** Is Active */
            is_active: boolean;
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at: string | null;
        };
        /** DemographicCreateRequest */
        DemographicCreateRequest: {
            /** Birth Year */
            birth_year: number | null;
            /** Gender */
            gender: string | null;
            /** Zip Code */
            zip_code: string | null;
        };
        /** DemographicReadResponse */
        DemographicReadResponse: {
            /** User Id */
            user_id: number;
            /** Birth Year */
            birth_year: number | null;
            /** Gender */
            gender: string | null;
            /** Zip Code */
            zip_code: string | null;
        };
        /** DemographicUpdateRequest */
        DemographicUpdateRequest: {
            /** Birth Year */
            birth_year: number | null;
            /** Gender */
            gender: string | null;
            /** Zip Code */
            zip_code: string | null;
        };
        /** DemographicUpdateResponse */
        DemographicUpdateResponse: {
            /** User Id */
            user_id: number;
            /** Birth Year */
            birth_year: number | null;
            /** Gender */
            gender: string | null;
            /** Zip Code */
            zip_code: string | null;
        };
        /** EntityCreateRequest */
        EntityCreateRequest: {
            /** Unique Id */
            unique_id: string;
            /** Type */
            type: number;
            /** Title */
            title: string;
            /** Images */
            images: string[];
            /** Tags */
            tags: components["schemas"]["TagRequest"][];
            /** Description */
            description?: string | null;
            /** Start Time */
            start_time?: string | null;
            /** End Time */
            end_time?: string | null;
            /** Latest Action Date */
            latest_action_date?: string | null;
            /** Latest Action Text */
            latest_action_text?: string | null;
        };
        /** EntityDeleteResponse */
        EntityDeleteResponse: {
            /** Success */
            success: boolean;
        };
        /** EntityFeedEntity */
        EntityFeedEntity: {
            /** Id */
            id: number;
            /** Type */
            type: number;
            /** Title */
            title: string;
            /** Images Json */
            images_json: string;
            /** Tags */
            tags: components["schemas"]["EntityFeedTag"][];
            /** Stances */
            stances: components["schemas"]["EntityFeedStance"][];
            /** Description */
            description?: string | null;
            /** Start Time */
            start_time?: string | null;
            /** End Time */
            end_time?: string | null;
            /** Latest Action Date */
            latest_action_date?: string | null;
            /** Latest Action Text */
            latest_action_text?: string | null;
        };
        /** EntityFeedStance */
        EntityFeedStance: {
            /** Id */
            id: number;
            /** Headline */
            headline: string;
            /** Average Rating */
            average_rating: number | null;
        };
        /** EntityFeedTag */
        EntityFeedTag: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Tag Type */
            tag_type: number;
        };
        /** EntityListResponse */
        EntityListResponse: {
            /** Entities */
            entities: components["schemas"]["EntityFeedEntity"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** EntityReadResponse */
        EntityReadResponse: {
            /** Id */
            id: number;
            /** Unique Id */
            unique_id: string;
            /** Type */
            type: number;
            /** Title */
            title: string;
            /** Images Json */
            images_json: string;
            /** Tags */
            tags: components["schemas"]["TagResponse"][];
            /** Description */
            description?: string | null;
            /** Start Time */
            start_time?: string | null;
            /** End Time */
            end_time?: string | null;
            /** Latest Action Date */
            latest_action_date?: string | null;
            /** Latest Action Text */
            latest_action_text?: string | null;
        };
        /** EntityStancesResponse */
        EntityStancesResponse: {
            /** Stances */
            stances: components["schemas"]["PaginatedStancesByEntityStance"][];
            next_cursor: components["schemas"]["PaginatedStancesByEntityCursor"] | null;
        };
        /** EntityUpdateRequest */
        EntityUpdateRequest: {
            /** Unique Id */
            unique_id?: string | null;
            /** Title */
            title?: string | null;
            /** Images */
            images?: string[] | null;
            /** Tags */
            tags?: components["schemas"]["TagRequest"][] | null;
            /** Description */
            description?: string | null;
            /** Start Time */
            start_time?: string | null;
            /** End Time */
            end_time?: string | null;
            /** Latest Action Date */
            latest_action_date?: string | null;
            /** Latest Action Text */
            latest_action_text?: string | null;
        };
        /** EntityUpdateResponse */
        EntityUpdateResponse: {
            /** Id */
            id: number;
            /** Unique Id */
            unique_id: string;
            /** Type */
            type: number;
            /** Title */
            title: string;
            /** Images Json */
            images_json: string;
            /** Description */
            description?: string | null;
            /** Start Time */
            start_time?: string | null;
            /** End Time */
            end_time?: string | null;
            /** Latest Action Date */
            latest_action_date?: string | null;
            /** Latest Action Text */
            latest_action_text?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ImageCreateRequest */
        ImageCreateRequest: {
            /** Stance Id */
            stance_id?: number | null;
            /** Entity Id */
            entity_id?: number | null;
            /** Profile Id */
            profile_id?: number | null;
            /** Mime Type */
            mime_type: string;
            /** B64 Image Content */
            b64_image_content: string;
        };
        /** ImageCreateResponse */
        ImageCreateResponse: {
            /** Public Url */
            public_url: string;
        };
        /** LoginRequest */
        LoginRequest: {
            /** Username */
            username: string;
            /** Password */
            password: string;
        };
        /** LogoutRequest */
        LogoutRequest: {
            /** Refresh Token */
            refresh_token: string;
        };
        /** NumRatingsResponse */
        NumRatingsResponse: {
            /** Num Ratings */
            num_ratings: number;
        };
        /** PaginatedStancesByEntityCursor */
        PaginatedStancesByEntityCursor: {
            /** Score */
            score: number;
            /** Id */
            id: number;
        };
        /** PaginatedStancesByEntityStance */
        PaginatedStancesByEntityStance: {
            /** Id */
            id: number;
            user: components["schemas"]["StanceFeedUser"];
            /** Headline */
            headline: string;
            /** Content Json */
            content_json: string;
            /** Num Comments */
            num_comments: number;
            /** Average Rating */
            average_rating: number | null;
            /** Num Ratings */
            num_ratings: number;
            /** My Rating */
            my_rating: number | null;
            /** Tags */
            tags: components["schemas"]["StanceFeedTag"][];
            /** Created At */
            created_at?: string | null;
        };
        /** PaginatedStancesByEntityStanceResponse */
        PaginatedStancesByEntityStanceResponse: {
            stance: components["schemas"]["PaginatedStancesByEntityStance"];
        };
        /** PaginatedStancesByUserStance */
        PaginatedStancesByUserStance: {
            /** Id */
            id: number;
            entity: components["schemas"]["StanceFeedEntity"];
            /** Headline */
            headline: string;
            /** Content Json */
            content_json: string;
            /** Num Comments */
            num_comments: number;
            /** Average Rating */
            average_rating: number | null;
            /** Num Ratings */
            num_ratings: number;
            /** My Rating */
            my_rating: number | null;
            /** Tags */
            tags: components["schemas"]["StanceFeedTag"][];
            /** Created At */
            created_at: string;
        };
        /** ProfileCreateRequest */
        ProfileCreateRequest: {
            /** Bio */
            bio: string | null;
            /** Avatar Url */
            avatar_url: string | null;
            /** Pinned Stance Id */
            pinned_stance_id: number | null;
        };
        /** ProfilePageResponse */
        ProfilePageResponse: {
            /** Username */
            username: string;
            /** Full Name */
            full_name: string;
            /** Follower Count */
            follower_count: number;
            /** Following Count */
            following_count: number;
            /** Following */
            following: boolean | null;
            /** Bio */
            bio: string | null;
            /** Avatar Url */
            avatar_url: string | null;
            /** Pinned Stance Id */
            pinned_stance_id: number | null;
            /** Pinned Stance Id Entity Id */
            pinned_stance_id_entity_id: number | null;
        };
        /** ProfileReadResponse */
        ProfileReadResponse: {
            /** User Id */
            user_id: number;
            /** Profile Id */
            profile_id: number;
            /** Bio */
            bio: string | null;
            /** Avatar Url */
            avatar_url: string | null;
            /** Pinned Stance Id */
            pinned_stance_id: number | null;
        };
        /** ProfileUpdateRequest */
        ProfileUpdateRequest: {
            /** Bio */
            bio?: string | null;
            /** Avatar Url */
            avatar_url?: string | null;
            /** Pinned Stance Id */
            pinned_stance_id?: number | null;
        };
        /** ProfileUpdateResponse */
        ProfileUpdateResponse: {
            /** User Id */
            user_id: number;
            /** Profile Id */
            profile_id: number;
            /** Bio */
            bio: string | null;
            /** Avatar Url */
            avatar_url: string | null;
            /** Pinned Stance Id */
            pinned_stance_id: number | null;
        };
        /** ReadStanceRatingResponse */
        ReadStanceRatingResponse: {
            /** Rating */
            rating?: number | null;
        };
        /** RefreshRequest */
        RefreshRequest: {
            /** Refresh Token */
            refresh_token: string;
        };
        /** RefreshResponse */
        RefreshResponse: {
            /** Access Token */
            access_token: string;
            /** Refresh Token */
            refresh_token: string;
        };
        /** SignupRequest */
        SignupRequest: {
            /** Username */
            username: string;
            /** Full Name */
            full_name: string;
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /** SignupResponse */
        SignupResponse: {
            /** Id */
            id: number;
            /** Username */
            username: string;
            /** Full Name */
            full_name: string;
            /** Email */
            email: string;
        };
        /** StanceCreateRequest */
        StanceCreateRequest: {
            /** Headline */
            headline: string;
            /** Content Json */
            content_json: string;
        };
        /** StanceCreateResponse */
        StanceCreateResponse: {
            /** Id */
            id: number;
            /** User Id */
            user_id: number;
            /** Entity Id */
            entity_id: number;
            /** Headline */
            headline: string;
            /** Content Json */
            content_json: string;
        };
        /** StanceFeedCursor */
        StanceFeedCursor: {
            /** Score */
            score: number | null;
            /** Id */
            id: number | null;
        };
        /** StanceFeedEntity */
        StanceFeedEntity: {
            /** Id */
            id: number;
            /** Type */
            type: number;
            /** Title */
            title: string;
            /** Images Json */
            images_json: string;
            /** Tags */
            tags: components["schemas"]["StanceFeedTag"][];
            /** Description */
            description?: string | null;
            /** Start Time */
            start_time?: string | null;
            /** End Time */
            end_time?: string | null;
        };
        /** StanceFeedRequest */
        StanceFeedRequest: {
            /**
             * Num Stances
             * @default 20
             */
            num_stances: number;
            /** Initial Stance Id */
            initial_stance_id: number | null;
            /** Entities */
            entities: number[] | null;
            cursor?: components["schemas"]["StanceFeedCursor"] | null;
        };
        /** StanceFeedResponse */
        StanceFeedResponse: {
            /** Stances */
            stances: components["schemas"]["StanceFeedStance"][];
            next_cursor?: components["schemas"]["StanceFeedCursor"] | null;
        };
        /** StanceFeedStance */
        StanceFeedStance: {
            /** Id */
            id: number;
            user: components["schemas"]["StanceFeedUser"];
            entity: components["schemas"]["StanceFeedEntity"];
            /** Headline */
            headline: string;
            /** Content Json */
            content_json: string;
            /** Num Comments */
            num_comments: number;
            /** Average Rating */
            average_rating: number | null;
            /** Num Ratings */
            num_ratings: number;
            /** My Rating */
            my_rating: number | null;
            /** Tags */
            tags: components["schemas"]["StanceFeedTag"][];
            /** Created At */
            created_at: string;
        };
        /** StanceFeedStanceResponse */
        StanceFeedStanceResponse: {
            stance: components["schemas"]["StanceFeedStance"];
        };
        /** StanceFeedTag */
        StanceFeedTag: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Tag Type */
            tag_type: number;
        };
        /** StanceFeedUser */
        StanceFeedUser: {
            /** Id */
            id: number;
            /** Username */
            username: string;
            /** Avatar Url */
            avatar_url: string | null;
        };
        /** StanceFollowingFeedResponse */
        StanceFollowingFeedResponse: {
            /** Stances */
            stances: components["schemas"]["StanceFeedStance"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** StanceListResponse */
        StanceListResponse: {
            /** Stances */
            stances: components["schemas"]["StanceReadResponse"][];
        };
        /** StanceRateRequest */
        StanceRateRequest: {
            /** Rating */
            rating?: number | null;
        };
        /** StanceRateResponse */
        StanceRateResponse: {
            /** Success */
            success: boolean;
        };
        /** StanceReadResponse */
        StanceReadResponse: {
            /** Id */
            id: number;
            /** User Id */
            user_id: number;
            /** Entity Id */
            entity_id: number;
            /** Headline */
            headline: string;
            /** Content Json */
            content_json: string;
            /** Average Rating */
            average_rating: number | null;
        };
        /** StanceUpdateRequest */
        StanceUpdateRequest: {
            /** Headline */
            headline?: string | null;
            /** Content Json */
            content_json?: string | null;
        };
        /** StanceUpdateResponse */
        StanceUpdateResponse: {
            /** Id */
            id: number;
            /** User Id */
            user_id: number;
            /** Entity Id */
            entity_id: number;
            /** Headline */
            headline: string;
            /** Content Json */
            content_json: string;
            /** Average Rating */
            average_rating: number | null;
        };
        /** TagRequest */
        TagRequest: {
            /** Name */
            name: string;
            /** Tag Type */
            tag_type: number;
        };
        /** TagResponse */
        TagResponse: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Tag Type */
            tag_type: number;
        };
        /** Token */
        Token: {
            /** Access Token */
            access_token: string;
            /** Token Type */
            token_type: string;
        };
        /** TokenResponse */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /** Refresh Token */
            refresh_token: string;
        };
        /** UserListResponse */
        UserListResponse: {
            /** Users */
            users: components["schemas"]["UserReadResponse"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** UserReadResponse */
        UserReadResponse: {
            /** Id */
            id: number;
            /** Username */
            username: string;
            /** Full Name */
            full_name: string;
            /** Email */
            email: string;
        };
        /** UserStancesResponse */
        UserStancesResponse: {
            /** Stances */
            stances: components["schemas"]["PaginatedStancesByUserStance"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** UserUpdateRequest */
        UserUpdateRequest: {
            /** Username */
            username?: string | null;
            /** Full Name */
            full_name?: string | null;
            /** Email */
            email?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_entities_endpoint_entities__get: {
        parameters: {
            query?: {
                num_stances_per_entity?: number;
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_entity_endpoint_entities__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EntityCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityReadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_entity_endpoint_entities__entity_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entity_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityReadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_entity_endpoint_entities__entity_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entity_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EntityUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityUpdateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_entity_endpoint_entities__entity_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entity_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityDeleteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_stances_endpoint_stances__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StanceListResponse"];
                };
            };
        };
    };
    get_stance_feed_endpoint_stances_feed_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StanceFeedRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StanceFeedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_stance_feed_endpoint_stances_following_feed_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StanceFollowingFeedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_user_stances_endpoint_users__user_id__stances__get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserStancesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_my_stance_rating_endpoint_entities__entity_id__stances__stance_id__my_rating_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entity_id: number;
                stance_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadStanceRatingResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_entity_stances_endpoint_entities__entity_id__stances__get: {
        parameters: {
            query?: {
                cursor_score?: number | null;
                cursor_id?: number | null;
                limit?: number;
            };
            header?: never;
            path: {
                entity_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityStancesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_stance_endpoint_entities__entity_id__stances__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entity_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StanceCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StanceCreateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_my_stance_for_entity_entities__entity_id__stances_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entity_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedStancesByEntityStanceResponse"] | null;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_stance_basic_endpoint_entities__entity_id__stances__stance_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entity_id: number;
                stance_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StanceReadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_stance_endpoint_entities__entity_id__stances__stance_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entity_id: number;
                stance_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StanceUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StanceUpdateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_stance_endpoint_entities__entity_id__stances__stance_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entity_id: number;
                stance_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_stance_endpoint_entities__entity_id__stances__stance_id__page_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entity_id: number;
                stance_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StanceFeedStanceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rate_stance_endpoint_entities__entity_id__stances__stance_id__rate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entity_id: number;
                stance_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StanceRateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StanceRateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_num_ratings_endpoint_entities__entity_id__stances__stance_id__num_ratings_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entity_id: number;
                stance_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NumRatingsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_current_user_endpoint_users_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserReadResponse"];
                };
            };
        };
    };
    update_current_user_endpoint_users_me_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserReadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    check_username_endpoint_users_username_taken_get: {
        parameters: {
            query: {
                username: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": boolean;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_user_endpoint_users__user_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserReadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_user_endpoint_users__user_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_demographic_endpoint_users__user_id__demographics_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DemographicReadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_demographic_endpoint_users__user_id__demographics_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DemographicUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DemographicUpdateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_demographic_endpoint_users__user_id__demographics_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DemographicCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DemographicReadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_profile_endpoint_users__user_id__profile_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileReadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_profile_endpoint_users__user_id__profile_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileUpdateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_profile_endpoint_users__user_id__profile_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileReadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_profile_page_endpoint_users__user_id__profile_page_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfilePageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    follow_user_endpoint_users__user_id__follow_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unfollow_user_endpoint_users__user_id__follow_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_followers_endpoint_users__user_id__followers_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number | null;
            };
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_following_endpoint_users__user_id__following_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number | null;
            };
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    is_following_endpoint_users__user_id__following__followed_user_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                followed_user_id: number;
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": boolean;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    signup_auth_signup_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignupRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignupResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    token_auth_token_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_token_auth_token_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Token"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_token_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefreshResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LogoutRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_password_auth_change_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_comments_endpoint_entities__entity_id__stances__stance_id__comments__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entity_id: number;
                stance_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommentListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_comment_endpoint_entities__entity_id__stances__stance_id__comments__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entity_id: number;
                stance_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommentCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommentReadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_comment_endpoint_entities__entity_id__stances__stance_id__comments__comment_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entity_id: number;
                stance_id: number;
                comment_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommentReadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_comment_endpoint_entities__entity_id__stances__stance_id__comments__comment_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entity_id: number;
                stance_id: number;
                comment_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommentUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommentUpdateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_comment_endpoint_entities__entity_id__stances__stance_id__comments__comment_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entity_id: number;
                stance_id: number;
                comment_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_comment_replies_endpoint_entities__entity_id__stances__stance_id__comments__comment_id__replies_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entity_id: number;
                stance_id: number;
                comment_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommentListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    react_to_comment_entities__entity_id__stances__stance_id__comments__comment_id__reaction_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entity_id: number;
                stance_id: number;
                comment_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommentReactionCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_comment_reaction_entities__entity_id__stances__stance_id__comments__comment_id__reaction_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entity_id: number;
                stance_id: number;
                comment_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_image_endpoint_images_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImageCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImageCreateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
